//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int eqp_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string used { get; set; }
        public string cost { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> v_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
